const fs = require('fs')
const takeWhile = require('lodash/takeWhile')
const dropWhile = require('lodash/dropWhile')

const KOANS_DIR = './src/koans/'
const filenames = [ 'assert'
                  ]
const koans     = []

filenames.forEach(filename => {
  const contents = fs.readFileSync(KOANS_DIR + filename, 'utf8')
  const meditations = contents.split(/\/\/ *SEP/)

  koans.push(
    { category:    filename
    , meditations: meditations.map(meditation => {
        const lines = meditation.trim().split(/\n+/)
        const description =
          takeWhile(lines, (line => /^ *\/\//.test(line)))
        .map(line => line.replace(/^\/\/ */, ''))
        // .join('\n')
        const code = dropWhile( lines
                              , (line => /^ *\/\//.test(line))
                              )
                        .join('\n')

        return { description, code }
  })
    // , meditations: contents.split(/\/\/ *SEP/)
    //                        .map(x => ({ code: x.trim() }))
    }
  )
})

fs.writeFileSync( KOANS_DIR + 'koans.js'
                ,   '/**\n'
                  + ' * This file was auto-generated by makeKoans.js script.\n'
                  + ' */\n'
                  + 'module.exports = '
                  + JSON.stringify(koans)
                )
